### ISSUE TITLE
Publish for Scala.js 1.0.0-RC2

### ISSUE THREAD

**Issue by mikla** [typelevel/discipline#136]
Hi,
As I see everything is ready for discipline to be published for Scala.js 1.0.0-RC2
Let's do it?

Thanks!

**Comment by travisbrown** [comment]
@mikla I think @larsrh did this last month for 1.0.2: https://repo1.maven.org/maven2/org/typelevel/discipline-core_sjs1.0-RC2_2.13/

The latest two discipline-scalatest RCs are also available for 1.0.0-RC2 (as are Cats and Simulacrum): https://github.com/typelevel/discipline-scalatest/releases/tag/v1.0.0-RC3

**Comment by mikla** [comment]
@travisbrown thank you!
