### ISSUE TITLE
New release with scala.js support

### ISSUE THREAD

**Issue by non** [typelevel/discipline#14]
Now that we have scala.js support in master, it would be great to get a release out there.

@larsrh, are you happy with the current state of master? Do you think it is releasable as-is?

**Comment by larsrh** [comment]
Yep, happy with it. I'm staging a release now.

**Comment by larsrh** [comment]
Thanks to #15 the `release` command is back again. Releasing for real now.

**Comment by non** [comment]
Awesome! :cake:

**Comment by larsrh** [comment]
:cake: to @InTheNow for his plugin! @non, feel free to bug me anytime you need a release :shipit:

**Comment by InTheNow** [comment]
@larsrh Not my plugin (although I did do an early one) - now using the official sjs one.
