### ISSUE TITLE
Release a version for Scala 2.12.0-M4

### ISSUE THREAD

**Issue by larsrh** [typelevel/discipline#18]
Required dependencies:

* [ ] scalacheck_2.12.0-M4
* [ ] specs2-core_2.12.0-M4

**Comment by xuwei-k** [comment]
ref https://github.com/etorreborre/specs2/issues/469

**Comment by alexandru** [comment]
You'd also need Scala.js, but version 0.6.8 was just published for 2.12.0-M4.
