### ISSUE TITLE
discipline 1.1.1 not available on scala.js and dotty

### ISSUE THREAD

**Issue by cquiroz** [typelevel/discipline#198]
It seems the latest version for dotty is not available in scalajs though it shows up on scala 2.13.
Would it be possible to include that combination in a release?

**Comment by larsrh** [comment]
We currently have some troubles cross-building Dotty+Scala.js. This affects quite a few Typelevel projects. We're working on it; hopefully it should be resolved with Dotty 3.0.0-M2.

**Comment by cquiroz** [comment]
Thanks for the info. I'm trying to convert monocle to munit and noted this detail, looking forward to the next release

**Comment by larsrh** [comment]
DottyJS support is also still lacking in MUnit: scalameta/munit#199
