### ISSUE TITLE
discipline effect

### ISSUE THREAD

**Issue by cquiroz** [typelevel/discipline#203]
Should there be a `discipline-effect` using https://github.com/typelevel/scalacheck-effect? If so I'm not sure if it should be a separate repo or included here

**Comment by larsrh** [comment]
I don't have an opinion on whether or not that integration library is needed. But if yes, it absolutely has to be a separate repository; otherwise we run into a cyclic dependency.

**Comment by djspiewak** [comment]
I'm actually not sure on this front. In general, proving any laws around effect already requires defining an `Eq[F[A]]` for the effect `F`; is that not fundamental? Would there really be a benefit in lifting a special `Eq` such that it can produce an `F[Boolean]`?
