### ISSUE TITLE
Please issue a 0.4.1 release to unblock alleycats

### ISSUE THREAD

**Issue by benhutchison** [typelevel/discipline#23]
Background: https://gitter.im/non/alleycats?at=57625efcdfb1d8aa45a3f9f0

This cant be sent via a PR since it creates a new branch in discipline, but heres the relevant diff:
https://github.com/typelevel/discipline/compare/v0.4...benhutchison:release/0.4.1

**Comment by larsrh** [comment]
Releasing now.

**Comment by larsrh** [comment]
Cherry-picked your 124200f as 1280a45a92d8e0e6582cedacf901e299bd8fdf6a and released 0.4.1.
