### ISSUE TITLE
Scalacheck is polluting end distributable

### ISSUE THREAD

**Issue by schrepfler** [typelevel/discipline#24]
I've noticed discipline imports scalacheck which then inadvertently leaks upstream as it's not in test scope (not sure about scalatest as I see it optional. Shouldn't it be set as test scope? (this got leaked into the scalajs distro as well which prompted me about it)

```
[info]     | +-org.typelevel:discipline_2.11:0.4 [S]
[info]     | | +-org.scalacheck:scalacheck_2.11:1.12.4 (evicted by: 1.12.5)
[info]     | | +-org.scalacheck:scalacheck_2.11:1.12.5 [S]
```

**Comment by larsrh** [comment]
I don't see how Scalacheck could be in test scope – look e.g. at [Laws.scala](https://github.com/typelevel/discipline/blob/v0.5/shared/src/main/scala/Laws.scala).

**Comment by larsrh** [comment]
To clarify: What's the dependency chain on your end, i.e., what pulls in `discipline` as a dependency?

**Comment by schrepfler** [comment]
Either algebra or cats, on the beach at the moment so I can't inspect the dependency tree ATM 😀
https://github.com/schrepfler/crdt-kit/blob/master/build.sbt

**Comment by larsrh** [comment]
The reason is that you're pulling in `cats-laws` via `cats`. If you don't want to do law checking or define your own laws, you can just pull in `cats-core` instead.
