### ISSUE TITLE
Release a version for Scala 2.12-RC2

### ISSUE THREAD

**Issue by julien-truffaut** [typelevel/discipline#27]

**Comment by larsrh** [comment]
This is already [done](https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22discipline_2.12.0-RC2%22). As of now, you can use `0.7.1` (which is compatible to `0.7`).

**Comment by julien-truffaut** [comment]
sorry I missed it, thanks @larsrh

**Comment by larsrh** [comment]
No worries!
