### ISSUE TITLE
Release for 2.13.0-M1

### ISSUE THREAD

**Issue by djspiewak** [typelevel/discipline#32]
Needed for https://github.com/typelevel/cats/issues/1648

**Comment by larsrh** [comment]
There's a Scalatest for 2.13/sjs missing. Should I release discipline without sjs support?

**Comment by djspiewak** [comment]
No.  I found the same issue.  Going to raise it with ScalaTest directly; I suspect they're going to need a 3.0.2.

**Comment by larsrh** [comment]
I used `3.0.3` though. Did you mean a `3.0.4`?

**Comment by djspiewak** [comment]
Oh didn't realize there was a 3.0.3.  I was trying with 3.0.1.  Either way, the sjs artifacts are still missing.

**Comment by larsrh** [comment]
WIP branch here: https://github.com/typelevel/discipline/tree/topic/2.13

**Comment by djspiewak** [comment]
Already an issue for it: https://github.com/scalatest/scalatest/issues/1152

**Comment by djspiewak** [comment]
@larsrh Looks like we would have failed the release on the basis of ScalaCheck even if ScalaTest had been out.

**Comment by aeons** [comment]
The current version doesn't work with the 3.9 releases of specs2, so this is most welcome :)

**Comment by larsrh** [comment]
Fixed by #34. Release running now.
