### ISSUE TITLE
incorrect scm url in pom.xml

### ISSUE THREAD

**Issue by xuwei-k** [typelevel/discipline#332]
https://repo1.maven.org/maven2/org/typelevel/discipline-core_3/1.5.0/discipline-core_3-1.5.0.pom

```xml
<scm>
  <url>https://github.com/vasilmkd/discipline</url>
  <connection>scm:git:https://github.com/vasilmkd/discipline.git</connection>
  <developerConnection>scm:git:git@github.com:vasilmkd/discipline.git</developerConnection>
</scm>
```

sbt-typelevel plugin issue?  🤔  /cc @armanbilge 

https://github.com/typelevel/sbt-typelevel/blob/3eb3f99e21c63d37e902826bae44bac7e45574a1/github/src/main/scala/org/typelevel/sbt/TypelevelGitHubPlugin.scala#L43-L73

**Comment by armanbilge** [comment]
Ah, sbt-typelevel assumes CI release in which case those are always set correctly 😕 I suppose it should unset them if publishing locally ...

**Comment by vasilmkd** [comment]
I have multiple git remotes set in all of my repos. `origin` points to my fork and `upstream` to Typelevel.

**Comment by vasilmkd** [comment]
@xuwei-k Do you want me to publish `discipline-core` 1.5.1 with the proper metadata or should we wait for a resolution in `sbt-typelevel`?
