### ISSUE TITLE
Switch to ScalaCheck 1.14.0

### ISSUE THREAD

**Issue by nigredo-tori** [typelevel/discipline#52]
There are some nice new features in 1.14.0 (for example, displaying/setting test seed), but it is binary incompatible with the previous version. This means that Discipline using 1.13.5 prevents us from using the current versions of both ScalaCheck and Specs2.

**Comment by wedens** [comment]
The problem is scala 2.10 support in discipline. It prevents using newer versions of specs2 with scalacheck 1.14.0 support.

**Comment by nigredo-tori** [comment]
[Discipline uses different specs2 versions](https://github.com/typelevel/discipline/blob/f5c145ff1a1b586c062e11c9bb00c60ea58dd137/build.sbt#L103-L109) for 2.10 and 2.11-2.13 now. We probably just need to bump the latter specs2 version.

**Comment by wedens** [comment]
> We probably just need to bump the latter specs2 version, and set up a similar split for scalacheck.

scalacheck version is the same for all specs2/scalatest versions. scalatest is still on 1.13.5. specializing 1.14.0 just for newer specs2 version will be too messy IMO.

**Comment by nigredo-tori** [comment]
> specializing 1.14.0 just for newer specs2 version will be too messy IMO.

Yes, that is a problem. We need to push https://github.com/scalatest/scalatest/issues/1368 through somehow.

**Comment by nigredo-tori** [comment]
> I recommend talking to the cats developers about dropping 2.10 support

As far as I can see from [this discussion](https://github.com/typelevel/cats/issues/2130), the consensus is that 2.10 would go away, but it certainly won't happen in 1.1.x. With libraries that wide-used, dropping compatibility with something takes ages.

What if we take a stab at it from another angle? It should be much easier to update specs2 3.x to the new scalacheck version.
