### ISSUE TITLE
Add support for Scala Native

### ISSUE THREAD

**Issue by kubukoz** [typelevel/discipline#57]
Potential blockers (that I know of):

- https://github.com/rickynils/scalacheck/issues/396

**Comment by sorenbug** [comment]
A Scalacheck for ScalaNative has been published by @lolgab iirc. What's the status on this issue currently?

**Comment by larsrh** [comment]
Fixed by #116. Release pending.

**Comment by larsrh** [comment]
`1.0.1` is out
