### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by analytically** [typelevel/discipline#76]
We're seeing NoSuchMethodError with

```
[error]   org.typelevel.discipline.specs2.mutable.Discipline.$anonfun$checkAll$1(Discipline.scala:17)
[error]   org.specs2.specification.core.Fragments$.$anonfun$foreach$1(Fragments.scala:144)
[error]   scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
[error]   scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
[error]   scala.collection.immutable.List.foldLeft(List.scala:89)
[error]   org.specs2.specification.core.Fragments$.foreach(Fragments.scala:144)
[error]   org.typelevel.discipline.specs2.mutable.Discipline.checkAll(Discipline.scala:16)
```

probably due to a old dependency on scalacheck-specs2 in discipline 0.10. Would a 0.11 release be possible?

**Comment by larsrh** [comment]
These are the dependency versions in 0.10: https://github.com/typelevel/discipline/blob/v0.10.0/build.sbt#L24-L26

Could also be a too new version? As far as I can tell, specs2 is still on 4.3.x.

**Comment by analytically** [comment]
Yeah I think they broke something in 4.3.6:

[error]   caused by java.lang.NoSuchMethodError: org.specs2.specification.dsl.mutable.ExampleDsl1$BlockExample.in(Lscala/Function0;Lorg/specs2/execute/AsResult;)Lorg/specs2/specification/core/Fragment;

**Comment by larsrh** [comment]
Okay, that could be a problem. @etorreborre, is 4.3.x supposed to be binary compatible?

**Comment by analytically** [comment]
Can confirm it's an issue specific to 4.3.6, with 4.3.5 it works as expected.

**Comment by etorreborre** [comment]
That's my fault I should have bumped the version to `4.4.0`, I indeed changed a part of the API, I'm sorry.

**Comment by analytically** [comment]
No worries Eric!

**Comment by larsrh** [comment]
Thanks @etorreborre for the clarification. I say we wait until a 4.4.x release and then I'll publish a new discipline release, too.

**Comment by etorreborre** [comment]
@larsrh I published `4.4.0`: https://github.com/etorreborre/specs2/releases/tag/SPECS2-4.4.0

**Comment by larsrh** [comment]
Thank you, Eric!

**Comment by larsrh** [comment]
Done.
