### ISSUE TITLE
Release version with updated dependencies.

### ISSUE THREAD

**Issue by non** [typelevel/discipline#9]
At this point ScalaCheck is on 1.12.2, ScalaTest is on 2.2.4, and Specs2 is on 3.6.

It would be great to update the dependencies and do a new release, to avoid getting too out-of-date.

**Comment by larsrh** [comment]
Updating & uploading to Sonatype now.

**Comment by larsrh** [comment]
@etorreborre You might want to have a look at f7b7da04366958ffb7478daba17679ae8a1b37cc, where I adapted to changes in specs2 3.x. It's probably slightly broken now; pull request appreciated :-)

**Comment by larsrh** [comment]
Released `v0.3`.
